services:
  frontend:
    container_name: just-post-frontend
    build: .
    ports:
      - 3000:3000
    networks:
      - just-post-network
    env_file:
      - ./src/environments/.env.prod

networks:
  just-post-network:
    external: true
